jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: chocolateen
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: vaugie_g
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: i_dont_know
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: nasso
          password: ${USER_NASSO_PASS}

jobs:
  - file: /usr/local/job_dsl.groovy