jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

jobs:
  - file: /usr/local/job_dsl.groovy