jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  remotingSecurity:
    enabled: true
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Read"
              - "Overall/Administer"
            assignments:
              - "chocolateen"
              - "admin"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Read"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Cancel"
              - "Job/Read"
              - "Job/Move"
            assignments:
              - "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"
            assignments:
              - "nasso"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: "admin"
        - id: chocolateen
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: vaugie_g
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: i_dont_know
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: nasso
          password: ${USER_NASSO_PASSWORD}

jobs:
  - file: /usr/local/job_dsl.groovy